name: SPORTTV 2 Stream Syncer

on:
  schedule:
    - cron: '0 */3 * * *'  # Toutes les 6 heures
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper selenium webdriver-manager
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          
      - name: Run extractor
        run: |
          python stream/script/SPORT_TV_2.py
          
      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add stream/
          git commit -m "🔄 Auto-update SportTV 2 stream"
          git push
