name: SPORTTV 2 Stream Syncer

on:
  schedule:
    - cron: '* */1 * * *'  # Toutes les 3 heures
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Installer dépendances
        run: pip install beautifulsoup4 requests
      
      - name: Run sync script
        run: python stream/script/SPORT_TV_2.py
      
      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git add stream/
          git config --global user.email "gamingrodrigo2009@hotmail.com"
          git config --global user.name "RodriIPTV6"
          git commit -m "Update SportTV 2 stream"
          git push origin HEAD:main
