name: TF1 Stream Syncer

on:
  schedule:
    - cron: '0 */3 * * *'  # Toutes les 3 heures
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
      
      - name: Run sync script
        run: python TF1.py
      
      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stream/
          git commit -m "🔄 Auto-sync TF1 - $(date +'%Y-%m-%d %H:%M UTC')"
          git push          git config --global user.name "IPTV Updater"
          git config --global user.email "updater@iptv.fr"
          git add stream/
          git commit -m "🔄 Automatic stream update $(date +'%Y-%m-%d %H:%M')"
          git push
