name: Professional Stream Updater

on:
  schedule:
    - cron: '0 */2 * * *'  # Toutes les 2 heures
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install advanced dependencies
        run: |
          pip install --upgrade pip
          pip install cloudscraper==1.2.60 urllib3==1.26.15
          
      - name: Run professional extractor
        run: python stream/tf1.m3u8
        
      - name: Push updates
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Professional Updater"
          git config --global user.email "updater@noreply.com"
          git add stream/tf1.m3u8
          git commit -m "🔄 Professional update - $(date +'%Y-%m-%d %H:%M')"
          git push
