name: Ultimate IPTV Updater

on:
  schedule:
    - cron: '0 */4 * * *'  # Toutes les 4 heures
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important pour l'historique Git complet

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'  # Activation du cache pour les dépendances

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stream extractor
        run: python stream/script/TF1.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "IPTV Updater"
          git config --global user.email "updater@iptv.fr"
          git add stream/
          git commit -m "🔄 Automatic stream update $(date +'%Y-%m-%d %H:%M')"
          git push
