name: Update M3U8 Stream TF1

on:
  schedule:
    - cron: '0 */3 * * *'  # Toutes les 3 heures
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # 🔥 Utilisation du secret ici

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run M3U8 extractor
        run: python stream/script/TF1.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # ⚠️ Nécessaire pour l'authentification git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stream/tf1.m3u8  # Chemin relatif vers le fichier
          git commit -m "Update M3U8 stream"
          git push https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
